import 'package:flutter/material.dart';

const lightTextTheme = TextTheme(
  bodyMedium: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 16,
      fontWeight: FontWeight.w400,
      color: Colors.black),
  bodySmall: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 14,
      fontWeight: FontWeight.w400,
      color: Colors.black),
  bodyLarge: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 18,
      fontWeight: FontWeight.w400,
      color: Colors.black),
  titleSmall: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 18,
      fontWeight: FontWeight.w600,
      color: Colors.black),
  titleLarge: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 24,
      fontWeight: FontWeight.w600,
      color: Colors.black),
  titleMedium: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 22,
      fontWeight: FontWeight.w600,
      color: Colors.black),
  labelLarge: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 20,
      fontWeight: FontWeight.w500,
      color: Colors.black),
  labelMedium: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 18,
      fontWeight: FontWeight.w500,
      color: Colors.black),
  labelSmall:TextStyle(
    fontFamily: 'Prompt',
    fontSize: 16,
    fontWeight: FontWeight.w500,
    color: Colors.black),
  displaySmall: TextStyle(
      fontFamily: 'Prompt',
      fontSize: 20,
      fontWeight: FontWeight.w400,
      color: Colors.black),
);
