// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBs5CuRTkFDVTuDmwMwoqpIknI6bYG3E0',
    appId: '1:144028262971:web:a721ca7acaa50c4743b21e',
    messagingSenderId: '144028262971',
    projectId: 'taskmanagement-10f8c',
    authDomain: 'taskmanagement-10f8c.firebaseapp.com',
    storageBucket: 'taskmanagement-10f8c.appspot.com',
    measurementId: 'G-2FRB48VT6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD89qm7ZlMKOtcY01WuRE5MPjt5fvPrR54',
    appId: '1:144028262971:android:efa7b905fc24499843b21e',
    messagingSenderId: '144028262971',
    projectId: 'taskmanagement-10f8c',
    storageBucket: 'taskmanagement-10f8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGttENoWsSjHF8ZnutxS9E2pSF6zfqs5A',
    appId: '1:144028262971:ios:2cf5a1cc2e08263943b21e',
    messagingSenderId: '144028262971',
    projectId: 'taskmanagement-10f8c',
    storageBucket: 'taskmanagement-10f8c.appspot.com',
    iosBundleId: 'com.example.roomMasterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGttENoWsSjHF8ZnutxS9E2pSF6zfqs5A',
    appId: '1:144028262971:ios:31717dc553c1e67343b21e',
    messagingSenderId: '144028262971',
    projectId: 'taskmanagement-10f8c',
    storageBucket: 'taskmanagement-10f8c.appspot.com',
    iosBundleId: 'com.example.roomMasterApp.RunnerTests',
  );
}
